AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RiftScribe Serverless Backend

Parameters:
  MatchDataBucketName:
    Type: String
  GeneratedImagesBucketName:
    Type: String
  SagaCacheTableName:
    Type: String
  RiotApiKey:
    Type: String
    NoEcho: true
    Description: Riot Games API key for fetching player data

Resources:

  ####################################################
  # IAM Role for Lambda
  ####################################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: RiftScribeLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${MatchDataBucketName}
                  - !Sub arn:aws:s3:::${MatchDataBucketName}/*
                  - !Sub arn:aws:s3:::${GeneratedImagesBucketName}
                  - !Sub arn:aws:s3:::${GeneratedImagesBucketName}/*
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SagaCacheTableName}
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ####################################################
  # Lambda Function
  ####################################################
  RiftScribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: handler.handler
      CodeUri: lambda/
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          MATCH_DATA_BUCKET: !Ref MatchDataBucketName
          GENERATED_IMAGES_BUCKET: !Ref GeneratedImagesBucketName
          SAGA_CACHE_TABLE: !Ref SagaCacheTableName
          RIOT_API_KEY: !Ref RiotApiKey

  ####################################################
  # API Gateway
  ####################################################
  RiftScribeApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RiftScribeAPI
      EndpointConfiguration:
        Types:
          - REGIONAL

  # Create /generate-saga resource
  GenerateSagaResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RiftScribeApi
      ParentId: !GetAtt RiftScribeApi.RootResourceId
      PathPart: generate-saga

  # POST method on /generate-saga
  GenerateSagaMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RiftScribeApi
      ResourceId: !Ref GenerateSagaResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RiftScribeFunction.Arn}/invocations

  # OPTIONS method for CORS preflight
  GenerateSagaOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RiftScribeApi
      ResourceId: !Ref GenerateSagaResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  RiftScribeApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GenerateSagaMethod
      - GenerateSagaOptionsMethod
    Properties:
      RestApiId: !Ref RiftScribeApi
      StageName: production

  ####################################################
  # Lambda → API Gateway Permission
  ####################################################
  RiftScribePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref RiftScribeFunction
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RiftScribeApi}/*

Outputs:
  RiftScribeApiEndpoint:
    Description: API URL
    Value: !Sub "https://${RiftScribeApi}.execute-api.${AWS::Region}.amazonaws.com/production/generate-saga/"
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt RiftScribeFunction.Arn
